version: '3'

services:
  db:
    container_name: cstsql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=cst
      - MYSQL_USER=cst
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  phpmyadmin:
    container_name: cstpma
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
  web:
    container_name: cstweb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www"
    ports:
      - 80:80
      - 443:443
    env_file: "./src/html/.env"
    depends_on:
      - db
